@startuml

class Products {

    - Long id;
    - String name;
    - String urlImg;
    - int stock;
    - double price;

    + set()
    + get()
}

class Users {

    - Long id;
    - boolean admin;
    - String firstName;
    - String lastName;
    - String urlImg;
    - String phone;
    - String email;
    - int balance;
    - String password;

    + set()
    + get()
}

class Categories {

    - Long id;
    - String name;

    + set()
    + get()
}

 Products "*" o-- "*" Categories
 Users "*" o-- "*" Products

@enduml